# 例外

## 例外とは

プログラムの実行中に何らかの異常が発生し、動作を続けられなくなった場合に特別なクラスが自動的にインスタンス化される。</br>
この特別なクラスの事を例外(Exception, エクセプション)と言い、基本的に例外が発生するとプログラムがエラー終了する。</br>
例外クラスは数十種類あり、それぞれ例外が発生する(例外が発生することを一般に “例外が投げられる” とも言う。理由は後述)箇所、場面によってその例外は異なる。</br>
例えば、ファイル読込に使うFileInputStreamクラスを用いてファイルの操作をする場合、仮に指定したファイルが存在しなかった時に、FileNotFoundExceptionという例外が発生する。</br>


## 例外処理

仮に例外が発生した場合でも、何らかの処理により正常な状態に復帰できる場合がある。</br>
例えば、特定のファイルが見つからず、FileNotFoundExceptionが発生した場合に、「ファイルが見つかりませんでした。もう一度パスを入力してください」と表示して再入力させるなど。</br>
こういった、例外が発生してもエラー終了させずに何らかの処理を続行させることを例外処理という。</br>
例外および例外を処理する機構はオブジェクト指向を取り入れた様々な言語で使われている。</br>


## Javaにおける例外

Javaにおいて、例外処理をするには try-catch文 を用いる。</br>
try句には例外が発生する可能性のある処理を記述し、もし実際に例外が投げられた場合はcatch句に処理が移行する。</br>
catch句への処理の移行は、try句の処理が残っていたとしても例外が発生すれば強制的に移行し、catch句の処理が終わった後でも続きから再開することは無い。</br>
```
try {
	/* 例外(Exception)が発生する可能性のある処理 */
} catch (Exception e){  /* 例外処理 */  }
```
例として、このような文をmain()中に書いていただきたい。</br>
```
FileInputStream fis = new FileInputStream(“hogehoge.err”);
```
“ハンドルされていない例外FileNotFoundException” と表示されてコンパイルが通らないはずである。</br>
FileInputStreamはファイル読込に関わるクラスだが、ファイルが存在しないとFileNotFoundExceptionを発生させる。</br>
次に、このプログラムのコンパイルを通し、エラー終了させない方法について解説する。</br>
先ほどのコードを以下のように編集していただきたい。</br>
```
try {
	FileInputStream fis = new FileInputStream(“hogehoge.err”);
	System.out.println(“ファイル読込に成功しました。”);
} catch (Exception e) {
	System.out.println(“エラー！”);
}
```
実行すると、「ファイル読み込みに成功しました」と表示されずに、「エラー！」と表示されるはずである。</br>
ここで、catchキーワードの直後にある丸括弧()の中に注目すると、Exceptionという記述がある。</br>
これは、そのcatch文の処理に入るのは、どの例外が発生したときなのかを表すものである。</br>
また、全ての例外クラスはExceptionクラスを継承しているため、以下のように記述するとどのような例外が発生した場合でもそのcatch句に処理が移行する。</br>
```
try{    /* 例外が発生する処理 */    }
catch (Exception e){
	e.printStackTrace();
}
```
例外が発生し、例外クラスをインスタンス化することをthrowといい(厳密には異なる)、例外が発生することを “例外が投げられる” もしくは”throwされる” という。
また、一つのtry句につきcatch句の数はいくつでもいいため、一つのtry句の中で複数種類のExceptionが投げられる可能性がある場合、以下のように記述することで、投げられた例外に応じた例外処理が可能である。</br>
```
try{    /* 複数種類の例外が投げられる可能性のある処理 */    }
catch(FileNotFoundException e){  /* ファイルが見つからなかった */  }
catch(IOException e){  /* IOで問題発生 */  }
catch(IllegalArgumentException e){  /* 引数がおかしい */  }
```


## 例外の種類
Javaにおける例外には大きく分けて以下の2種類がある。</br>
* 検査例外
    * 検査例外の発生する処理は必ずtry句で囲い、適切なcatch句を記述して例外を捕捉しなければならない
* 非検査例外
    * 非検査例外の発生する処理はtry句で囲う必要はない</br>

基本的に、検査例外はプログラマーが回避しようのない場合に用いられ、非検査例外は回避することができる場合に投げられる</br>
よって、プログラムが正確に構築できていれば非検査例外が発生することは基本的に無い。</br>


## 演習課題
### 課題1
Exercise6_1クラスを作成し、その中にmain()メソッドを追加する。</br>
Scannerクラスのnext〇〇()系のメソッドは、標準入力からの入力を〇〇に変換できなかった場合にInputMismatchExceptionを投げる。</br>
#### Exercise6_1クラス
* main()
    * ScannerのnextDouble()メソッドを用いて64bit浮動小数点数を入力させ、入力後その値を表示させなさい
    * ただし、浮動小数点数以外の値を入力したときにはInputMismatchExceptionが投げられるため、これをcatchし ”エラー.” と出力しなさい
#### 実行結果
```
小数値を入力してください:
> hogehoge
エラー.

小数値を入力してください:
> 42.195
入力した値:  42.195
```

### 課題2
Randomクラスは乱数を提供するクラスである。</br>
Randomクラスのインスタンスメソッド、</br>
`int nextInt(int max)`
を用いることで、 0以上max未満の値をランダムに返す。</br>
```
	Random random = new Random();
	System.out.println(random.nextInt(100));		// 0~99の値を表示
```
#### Exercise6_2クラス
* main()
    * ArrayList<Integer>の中に1~6のランダムな値を持つIntegerクラスのインスタンスを5個追加しなさい
    * その後Scannerを用いて標準入力に入力された整数値を取得しint型のindexに代入し、上で作ったArrayList<Integer>のindex番目の値を表示させなさい
    * ただし、ArrayListの範囲外の要素にアクセスしようとしたときに投げられるExceptionをcatchし、適切に処理せよ(Exception自体をcatchせず、具体的な〇〇Exceptionをcatchしなさい)
#### 実行結果
```
さいころを5つ振りました.
何番目のさいころの値を確認しますか？
> 12
ArrayListの範囲外アクセスを確認しました.
プログラムを終了します.
```


## 課題が終わった学生

次回はJavaのまとめを行います。</br>
DB編に入る前にもう一度Javaの基礎を確認するための時間ですので、この時間で基本文法を毎回調べる必要がないくらいまでは知識をつけておきましょう。</br>
DBでは取得した値をListに詰め込んだり、アクセス時に例外が発生したりと、これまでの内容が当たり前のように出てきます。</br>
また、DBを使用した場合の例外処理では、</br>
	`try-with-resource`</br>
という通常のtry-catchとは若干異なる例外処理を行うため、事前に調べておくと良いかもしれません。</br>
